# INDEX

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
# if torch.cuda.is_available:
#     print(f"GPU available, using device:{torch.cuda.get_device_name()}")
# else:
#     print(("running on CPU"))

##CREATING TENSORS

In [ ]:
t1=torch.empty(3,2,1)
print(t1)

tensor([[[4.1994e-29],
         [0.0000e+00]],

        [[3.5461e-33],
         [4.4816e-41]],

        [[8.9683e-44],
         [0.0000e+00]]])


In [ ]:
type(t1)

torch.Tensor

In [ ]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.rand(2,3)

tensor([[0.4758, 0.3212, 0.3951],
        [0.8257, 0.5399, 0.4911]])

In [ ]:
#manual seed: reproducability


In [ ]:
#torch.tensor: creating custom tensor

In [ ]:
#dimensions of a tensor
t1.shape

torch.Size([3, 2, 1])

In [ ]:
torch.empty_like(t1)

tensor([[[8.8415e-29],
         [0.0000e+00]],

        [[4.2878e-29],
         [0.0000e+00]],

        [[1.1210e-43],
         [0.0000e+00]]])

In [ ]:
torch.zeros_like(t1)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]])

In [ ]:
torch.rand_like(t1)

tensor([[[0.7580],
         [0.9512]],

        [[0.2884],
         [0.8575]],

        [[0.0243],
         [0.8953]]])

In [ ]:
print(t1.dtype)

torch.float32


In [ ]:
t2=torch.rand_like(t1)
print(t2)
print(t2.dtype)

tensor([[[0.8901],
         [0.5187]],

        [[0.2217],
         [0.1081]],

        [[0.4453],
         [0.1908]]])
torch.float32


In [ ]:
t3=torch.rand_like(t1,dtype=torch.float16)
print(t3)
print(t3.dtype)

tensor([[[0.2183],
         [0.8071]],

        [[0.0527],
         [0.8672]],

        [[0.2617],
         [0.9341]]], dtype=torch.float16)
torch.float16


##Operations on Tensors


*   Element wise matrix ops: a+2,a/2,a*3, a%2, a**2 etc.(each element is changed)
*   Tensor(matrix) ops: add,sub, etc. (a+b,a-b,a*b,a**b,a/b,a%b)
*   Tensor modifications: abs,floor,ceil,round,clamp [ by clipping them in a defined range]
*   Reduction of tensors: sum, mean, median, max, min, product, std, argmin, argmax, var
*  dim=0-> along columns, dim=1->along rows
* matrix ops: matmul, dot, transpose, det, inverse
* special ops: softmax, relu, log, expo, etc.
*   In-place Operations: to perform some op inplace and save space, a+b -> a.add_(b), torch.relu(a) -> a.relu_()
*   Copying tensor: 1. a=b, creates a shallow copy, 2. a=b.clone() deep copy
*   Reshaping tensors: flatten, reshape, permute(permute dimensions to reshape), unsqueeze(adds dimension at provided position), squeeze
* pytorch tensor to numpy: a.numpy()
* numpy array to tensor: torch.from_numpy(np_arr_name)

##Using GPU

In [ ]:
torch.cuda.is_available()

False

In [ ]:
device=torch.device('cuda')

In [ ]:
# a=torch.rand(2,3)
# b=a.to(device)

In [ ]:
# c=torch.zeros((1,5),device=device)
# print(c)

##AUTOGRAD
Autograd is a core component of PyTorch that provides automatic differentiation for tensor
operations. It enables gradient computation, which is essential for training machine learning
models using optimization algorithms like gradient descent.

In [ ]:
#when creating a tensor, to enable autograd we set requires_grad=True
#any tensor made by operating on this tensor has gradient tracking enabled
#to disable gradient tracking use x.detach()
#tensor_name.backward()->performs gradient calculation
#autograd basically maintaing the computational graph and iterated backward accordingly

# **Pytorch Training Pipeline**

1. manually
2. using nn module
3. also using dataset and dataloader

## Manually building a simple tarining pipeline

###getting data

In [ ]:
import pandas as pd
import numpy as np
import torch
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
df.drop(['id','Unnamed: 32'],axis=1,inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

###test and train split

In [ ]:
x_train,x_test,y_train,y_test= train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,train_size=0.8,shuffle=True)

In [ ]:
#df.iloc[:,x:y]->all rows and clmn from index x to y

###scaling

In [ ]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

###label encoding

In [ ]:
label_encoder=LabelEncoder()
y_train=label_encoder.fit_transform(y_train)
y_test=label_encoder.fit_transform(y_test)

In [ ]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0])

###converting np arrs to tensors

In [ ]:
x_train_tensor=torch.from_numpy(x_train.astype(np.float32))
x_test_tensor=torch.from_numpy(x_test.astype(np.float32))
y_train_tensor=torch.from_numpy(y_train.astype(np.float32))
y_test_tensor=torch.from_numpy(y_test.astype(np.float32))

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

##Defining Model

###Manual model

In [ ]:

class myManualNN():
  def __init__(self,X):
      self.weights=torch.rand(X.shape[1],1,dtype=torch.float32,requires_grad=True)
      self.bias=torch.zeros(1,dtype=torch.float32,requires_grad=True)

  def forward(self,X):
      z=torch.matmul(X,self.weights)+self.bias
      y_pred=torch.sigmoid(z)
      return y_pred

  def loss_function(self,y_pred,y):
      epsilon=1e-7
      y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
      loss=-(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
      return loss

In [ ]:
learning_rate=0.1
epochs=25

###training pipeline

In [ ]:
model=myManualNN(x_train_tensor)

#training loop
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(x_train_tensor)
  #loss calc
  loss=model.loss_function(y_pred,y_train_tensor)
  #backprop
  loss.backward()
  #update weights: no_grad() temporarily switches off gardinet tracking as wight update is not a part of the gradient calculation and will lead to wrong gradients and huge computational geraph
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad
  #clear grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  #logging
  print(f"epoch:{epoch+1}, loss:{loss}")

epoch:1, loss:3.4145374298095703
epoch:2, loss:3.2741005420684814
epoch:3, loss:3.1322333812713623
epoch:4, loss:2.985889434814453
epoch:5, loss:2.839019536972046
epoch:6, loss:2.6915414333343506
epoch:7, loss:2.535857677459717
epoch:8, loss:2.3794519901275635
epoch:9, loss:2.222043752670288
epoch:10, loss:2.059072971343994
epoch:11, loss:1.8999063968658447
epoch:12, loss:1.7463856935501099
epoch:13, loss:1.6037299633026123
epoch:14, loss:1.473178505897522
epoch:15, loss:1.3559000492095947
epoch:16, loss:1.2526912689208984
epoch:17, loss:1.1639596223831177
epoch:18, loss:1.0897117853164673
epoch:19, loss:1.0291861295700073
epoch:20, loss:0.9806574583053589
epoch:21, loss:0.9419994354248047
epoch:22, loss:0.9111900925636292
epoch:23, loss:0.8864228129386902
epoch:24, loss:0.8661686182022095
epoch:25, loss:0.849229097366333


In [ ]:
model.weights

tensor([[ 1.1265e-01],
        [ 4.7908e-01],
        [-3.5905e-01],
        [-2.9723e-01],
        [-3.3882e-01],
        [ 1.8301e-02],
        [ 3.3364e-01],
        [ 3.0165e-04],
        [ 2.1903e-01],
        [ 4.1629e-01],
        [ 3.0772e-01],
        [ 5.5099e-01],
        [-1.9376e-01],
        [-2.9569e-01],
        [-1.1170e-01],
        [-6.9502e-02],
        [-3.0550e-01],
        [-8.2007e-02],
        [-1.5933e-01],
        [ 1.2727e-01],
        [ 2.8613e-01],
        [ 2.8041e-01],
        [ 8.0810e-02],
        [ 3.1047e-03],
        [ 5.6643e-02],
        [-5.1776e-01],
        [ 1.8982e-01],
        [-9.3974e-03],
        [ 5.2481e-01],
        [-9.1040e-02]], requires_grad=True)

In [ ]:
model.bias

tensor([-0.1749], requires_grad=True)

###Evalutaion

In [ ]:
with torch.no_grad():
  y_pred_test=model.forward(x_test_tensor)
  y_pred_test=(y_pred_test>0.9).int()
  # print(y_pred)
  accuracy=(y_pred_test==y_test_tensor).float().mean()
  print(f"accuracy:{accuracy}")

accuracy:0.6141889691352844


###using the nn module

In [ ]:
import torch.nn as nn

class myNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
loss_function=nn.BCELoss()

In [ ]:
model=myNN(x_train_tensor.shape[1])

optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

#otherwise loss function wont work
print(y_train_tensor.shape)
print(y_pred.shape)
y_train_tensor.unsqueeze_(1)
print(y_train_tensor.shape)

for epoch in range(epochs):
  y_pred=model(x_train_tensor)
  loss=loss_function(y_pred,y_train_tensor)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  print(f"Epoch: {epoch+1}, Loss: {loss}")

torch.Size([455])
torch.Size([455, 1])
torch.Size([455, 1])
Epoch: 1, Loss: 0.6631284356117249
Epoch: 2, Loss: 0.30881693959236145
Epoch: 3, Loss: 0.21019235253334045
Epoch: 4, Loss: 0.1618548333644867
Epoch: 5, Loss: 0.13066105544567108
Epoch: 6, Loss: 0.10983060300350189
Epoch: 7, Loss: 0.09630664438009262
Epoch: 8, Loss: 0.08733972907066345
Epoch: 9, Loss: 0.08128278702497482
Epoch: 10, Loss: 0.0771946981549263
Epoch: 11, Loss: 0.07446359843015671
Epoch: 12, Loss: 0.07264795154333115
Epoch: 13, Loss: 0.0714142918586731
Epoch: 14, Loss: 0.0705106109380722
Epoch: 15, Loss: 0.06975433975458145
Epoch: 16, Loss: 0.06902525573968887
Epoch: 17, Loss: 0.06825756281614304
Epoch: 18, Loss: 0.06742903590202332
Epoch: 19, Loss: 0.06654823571443558
Epoch: 20, Loss: 0.06564172357320786
Epoch: 21, Loss: 0.0647432878613472
Epoch: 22, Loss: 0.06388571858406067
Epoch: 23, Loss: 0.0630955770611763
Epoch: 24, Loss: 0.062390342354774475
Epoch: 25, Loss: 0.06177762895822525


##Dataset & DataLoader (+complete final pipeline{last cell})


**Dataset Class**

The Dataset class is essentially a blueprint. When you create a
custom Dataset, you decide how data is loaded and returned.
It defines:
* __init__() which tells how data should be loaded.
* __len__() which returns the total number of samples.
* __getitem__(index) which returns the data (and label) at the
given index.

**DataLoader Class**

The DataLoader wraps a Dataset and handles batching, shuffling,
and parallel loading for you.

**DataLoader Control Flow:**

At the start of each epoch, the DataLoader (if shuffle=True)
shuffles indices(using a sampler).
* It divides the indices into chunks of batch_size.
for each index in the chunk, data samples are fetched from
the Dataset object
* The samples are then collected and combined into a batch
(using collate_fn)
* The batch is returned to the main training loop

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self, features,labels):
    self.features=features
    self.labels=labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    #can do required tranformations here
    return self.features[index],self.labels[index]

In [ ]:
train_dataset=CustomDataset(x_train_tensor,y_train_tensor)
test_dataset=CustomDataset(x_test_tensor,y_test_tensor)

In [ ]:
type(train_dataset)

__main__.CustomDataset

In [ ]:
len(train_dataset)

455

In [ ]:
len(test_dataset)

114

In [ ]:
train_dataset[0]

(tensor([-1.3086, -0.5955, -1.2764, -1.1005, -0.7937, -0.2351, -0.0555, -0.6676,
          0.7939,  1.1314, -0.8341, -0.5177, -0.7510, -0.6516, -0.3748,  0.4562,
          0.5522, -0.5313, -0.3396,  0.0445, -1.1624, -0.4617, -1.0937, -0.9475,
         -0.3882,  0.5258,  0.7416, -0.5032,  0.1435,  0.7333]),
 tensor([0.]))

In [ ]:
train_dataloader=DataLoader(train_dataset,batch_size=8,shuffle=True)
test_dataloader=DataLoader(test_dataset,batch_size=8,shuffle=True)

In [ ]:
type(train_dataloader)

torch.utils.data.dataloader.DataLoader

In [ ]:
len(train_dataloader)

57

In [ ]:
train_dataloader

In [ ]:
model=myNN(x_train_tensor.shape[1])

optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

#using dataloader: earlier each epoch trained on whole data at once, now each epoch will train on whole data but in parts i.e. batches
for epoch in range(epochs):
  for features, labels in train_dataloader:
    y_pred=model(features)
    loss=loss_function(y_pred,labels)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  #loss.item() shpuld be used instead of loss as it detaches the value from the computation graoh, so in case an operation is being performed its detached.
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.01584244705736637
Epoch: 2, Loss: 0.003963633440434933
Epoch: 3, Loss: 0.04013312608003616
Epoch: 4, Loss: 0.4346337616443634
Epoch: 5, Loss: 0.048714395612478256
Epoch: 6, Loss: 7.743115929770283e-06
Epoch: 7, Loss: 0.00021174162975512445
Epoch: 8, Loss: 0.017437446862459183
Epoch: 9, Loss: 0.03283902257680893
Epoch: 10, Loss: 4.920953529108374e-07
Epoch: 11, Loss: 0.46664443612098694
Epoch: 12, Loss: 0.00010876671149162576
Epoch: 13, Loss: 4.4594173232326284e-05
Epoch: 14, Loss: 2.3592274374095723e-06
Epoch: 15, Loss: 0.041708849370479584
Epoch: 16, Loss: 0.00019211764447391033
Epoch: 17, Loss: 4.3558416109590326e-06
Epoch: 18, Loss: 0.0001698427222436294
Epoch: 19, Loss: 0.0017464213306084275
Epoch: 20, Loss: 5.4735039611841785e-08
Epoch: 21, Loss: 2.2629149043496e-06
Epoch: 22, Loss: 0.00033653475111350417
Epoch: 23, Loss: 9.777094192031655e-07
Epoch: 24, Loss: 0.045538563281297684
Epoch: 25, Loss: 0.0002596831473056227


* model.train() → training mode

* model.eval() → inference mode (dropout off, batchnorm uses running stats, doesnt switch off grad calc)

* Use torch.no_grad() as well if you don’t need gradients.

In [ ]:
#model evaluation using test loader
#sets model in evaluation mode: difference in cases like dropout and batch_niorm mean and variance
model.eval()
accuracy_list=[]
for features,label in test_dataloader:
  pred_label=model(features)
  pred_label=(pred_label>0.9).int()#converting probabilities to binary prediction
  batch_accuracy=(pred_label.view(-1)==label).float().mean().item()
  accuracy_list.append(batch_accuracy)

print(accuracy_list)
accuracy=sum(accuracy_list)/len(accuracy_list)
print(f"accuracy: {accuracy:.2f}")

[1.0, 1.0, 1.0, 1.0, 1.0, 0.875, 1.0, 1.0, 1.0, 0.75, 1.0, 0.875, 1.0, 1.0, 1.0]
accuracy: 0.97
